apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  TMDB_TOKEN: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKaGRXUWlPaUptTlRSaVl6VTBZbVpoT1RVNE5qaGxObVF3T1dJd1l6UTJPV1ZtT0dObE9TSXNJbTVpWmlJNk1UYzNOakUyTURBNU55NHpPVE1zSW5OMVlpSTZJalk1WkdVd1pEWXhZVEV3TkRrM01EZGhOak0xT1RRMk1DSXNJbk5qYjNCbGN5STZXeUpoY0dsZmNtVmhaQ0pkTENKMlpYSnphVzl1SWpveGZRLkdTWmFEQnlUck5LbTg3VkREYXFYUEd1cGR6ZDdKbkxmSDcycndHNkdGQ1U=
  POSTGRES_PASSWORD: dWJ1bnR1MTQ=
  DATABASE_URL: cG9zdGdyZXNxbDovL2VidGk6dWJ1bnR1MTRAZGItc2VydmljZTo1NDMyL3dhdGNobmV4dF9kYg==

